# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    admin.category:
        class: BlogBundle\Admin\CategoryAdmin
        arguments: [~, BlogBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.blog_post:
        class: BlogBundle\Admin\PostsAdmin
        arguments: [~, BlogBundle\Entity\Posts, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Posts }
