BlogBundle_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
    options:
        _locale: fr


#section about
BlogBundle_about:
    path: /about
    defaults: { _controller: BlogBundle:Content:about }
    requirements:
        _method:  GET
        _locale: en|fr

#section contact
BlogBundle_contact:
    path: /contact
    defaults: { _controller: BlogBundle:Content:contact, _locale: fr }
    requirements:
        _method:  GET|POST
        _locale: en|fr

#showing Articles
BlogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: BlogBundle:Articles:show }
    requirements:
        _method:  GET
        id: \d+
        _locale: en|fr

#create comment
BlogBundle_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
        _locale: en|fr
